---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myapache-frontend
  namespace: myapache
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: myapache
      layer: frontend
  replicas: 2
  revisionHistoryLimit: 5
  template: 
    metadata:
      labels:
        app: myapache
        layer: frontend
    spec:
      containers:
      - name: myapache-frontend-conatiner
        image: vibhavsaluja2019/myapache-frontend:4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"

