---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: myapache-deployment-hpa
  namespace: myapache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapache-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
